name: Trigger auto deployment for fixr-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.FIXRBACKEND_AZURE_CREDENTIALS }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.FIXRBACKEND_REGISTRY_USERNAME }}
          password: ${{ secrets.FIXRBACKEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.FIXRBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FIXRBACKEND_REGISTRY_PASSWORD }}
          containerAppName: fixr-backend
          resourceGroup: exinta-tria
          imageToBuild: docker.io/${{ secrets.FIXRBACKEND_REGISTRY_USERNAME }}/fixr-backend:${{ github.sha }}